### ISSUE TITLE
API Key copy button sometimes doesn't copy the &parameter=

### ISSUE THREAD

**Issue by peteroxil** [OxfordInfoLabs/kinintel#1]
In the API Connection page of DAP, the API Key for HTTPS copy to clipboard button is inconsistent in what it copies.

![image](https://github.com/OxfordInfoLabs/kinintel/assets/90187376/746fe7e2-306d-44ad-bd50-e6fd011108ad)

Steps to reproduce:
- Create an API Key
- Create a Parameterised datasource
- Create an API Connection to your datasource, including the parameter
- Navigate to a different page
- Navigate to the API connections
- Click on the Copy button in the bottom right corner of the HTTPS
- Paste it somewhere
- The result will be missing the final parameter snippet

![image](https://github.com/OxfordInfoLabs/kinintel/assets/90187376/ab35b527-54f8-480c-9a68-f80432e09104)

If you click copy again, the final snippet will be there.

**Comment by NathanOXIL** [comment]
This has been changed to use native navigator clipboard object.
