### ISSUE TITLE
Imported Data duplicate entries

### ISSUE THREAD

**Issue by peteroxil** [OxfordInfoLabs/kinintel#16]
In the import data section of the DAP, if you have duplicate entries in your attempted new datasource, and you click Save and Exit, you will leave the page (with an error briefly appearing at the top of the page).

Expected Behaviour: Some kind of warning before you are navigated off this page. Perhaps Save and Exit wouldn't navigate you away from the page, or perhaps you'd be prompted to "Replace if there are duplicate primary keys and continue?" (this is the usual cause of SQL error).

To replicate:
![image](https://github.com/OxfordInfoLabs/kinintel/assets/90187376/e6f9aa27-2cf7-4043-8a39-6cd49f30ece6)

**Comment by NathanOXIL** [comment]
This whole area has been overhauled with a new import process. By default all datasources are created with a hidden auto increment field, which will prevent this happening.
