### ISSUE TITLE
Bug in creation of imported data from scratch

### ISSUE THREAD

**Issue by peteroxil** [OxfordInfoLabs/kinintel#18]
To reproduce:
- Create a new datasource in imported data
- Delete until there is one column
- Rename this column and make it the primary key
- Add new rows of data
- Click save

Expected behaviour:
The dataset is saved successfully.

Actual:
Error appears. "Base table or view already exists"

![image](https://github.com/OxfordInfoLabs/kinintel/assets/90187376/480ca199-b3d9-429c-a1a0-7c2a82610f58)

**Comment by NathanOXIL** [comment]
This will also have been resolved through the recent refactor.
