### ISSUE TITLE
Editing query join no longer starts from previous state

### ISSUE THREAD

**Issue by peteroxil** [OxfordInfoLabs/kinintel#21]
When editing a query, if you make a join, previously, going back into that join would jump to the second page of the join logic with the filters already filled in. Now, going to the join doesn't remember any of the existing information about the join.

![image](https://github.com/OxfordInfoLabs/kinintel/assets/90187376/490e83b0-2047-4de8-9bd3-2f096ee76401)

**Comment by peteroxil** [comment]
Also, **Selected Source** is missing in the following screen

<img width="537" alt="image" src="https://github.com/OxfordInfoLabs/kinintel/assets/90187376/c5fce4ac-7f58-48dc-bf96-2e0ab89c2fc1">

**Comment by NathanOXIL** [comment]
This has been fixed and pushed to Main. Will be included in the next release
