### ISSUE TITLE
Add a symbol for NULL entries in query view.

### ISSUE THREAD

**Issue by peteroxil** [OxfordInfoLabs/kinintel#23]
Currently, if you run a query one of the results is NULL, nothing is displayed in the cell. This means it's impossible to distinguish between the empty string and null values on the user side.

Expected Behaviour: Show some icon/symbol/the world null highlighted in some way/other indication of null entry in the cell.

This would improve clarity for users.

**Comment by NathanOXIL** [comment]
This has been done - will be included in the next release
