### ISSUE TITLE
Add tooltip in Chart editor to tell the user where to edit Colour Palettes

### ISSUE THREAD

**Issue by peteroxil** [OxfordInfoLabs/kinintel#27]
When editing a chart, it is not obvious to the user where to edit the colour palettes for a project. I think adding a tooltip (saying: "Edit colour palettes in DAP Settings -> Project Settings") to these chart editors would improve user experience.

![image](https://github.com/user-attachments/assets/08daa97b-5bf5-4ccf-bd5d-c9d7c1f4d765)

**Comment by NathanOXIL** [comment]
A notice is now displayed to the user if no palettes have been created - with a link to project settings to create one. This will be included in the next release
