### ISSUE TITLE
Cannot create new Alert Group

### ISSUE THREAD

**Issue by internOxil** [OxfordInfoLabs/kinintel#29]
In the Alert Group creation menu, when creating a Alert Group, the save changes button does nothing as the button is disabled. 

![Screenshot 2024-07-19 at 12 39 15](https://github.com/user-attachments/assets/9579224e-db79-4226-b1c0-1baf8550b785)
Alert Group creation menu

![Screenshot 2024-07-19 at 12 30 07](https://github.com/user-attachments/assets/afb73585-edfa-454d-9cd4-f31231069419)
Network Tab empty even after the button is clicked

![Screenshot 2024-07-19 at 12 31 14](https://github.com/user-attachments/assets/87c0b614-99aa-4b68-b329-ea0c5e9547b1)
HTML code showing the button is disabled

This menu should be disabled until Alert Groups are fixed

**Comment by NathanOXIL** [comment]
Time periods are required. I have now indicated this in the GUI
