### ISSUE TITLE
When snapshots / query cache builds fail there should be a view error functionality with retry options.

### ISSUE THREAD

**Issue by mrobertshaw** [OxfordInfoLabs/kinintel#32]

**Comment by mrobertshaw** [comment]
I've added the backend data for this and made the failed badge cursor pointer ready for a pop up to be triggered.

It would be good to catch a number of known cases (too many columns, too large index) and provide helpful resolution tips as well as a retry for the query cache case (where there is no run button).

**Comment by NathanOXIL** [comment]
This should be done now. On the query-gui-updates branch
