### ISSUE TITLE
Add new functionality to expose parameters defined in dashboard widget queries at the widget level for filtering at the widget level rather than the whole dashboard level

### ISSUE THREAD

**Issue by mrobertshaw** [OxfordInfoLabs/kinintel#38]
This should apply to any widget type (not just tables) and would add a filter bar at the top if parameters are exposed.  

Suggest adding it to Header Settings (see mock up !)

![Parameter Example](https://github.com/user-attachments/assets/626a50f4-9904-48e8-acc9-d0e6673f53e8)

**Comment by NathanOXIL** [comment]
This has now been completed and will be included in the next release
