### ISSUE TITLE
Reordering of transformations in the query editor means that their deletes don't match

### ISSUE THREAD

**Issue by peteroxil** [OxfordInfoLabs/kinintel#42]
When you add a filter in between two transformations:
![image](https://github.com/user-attachments/assets/6dc8e685-5142-4d26-a53c-62383ce6f59c)
the delete (x) buttons which are on each individual transformation no longer correspond to their own transformations. For example, trying to delete the last transformation deletes the first transformation.
![image](https://github.com/user-attachments/assets/4ee3eefe-e5ca-4e42-a289-c7e87d12d4c0)
![image](https://github.com/user-attachments/assets/3b8cc803-56c1-47a0-9f8d-c3119104de61)
![image](https://github.com/user-attachments/assets/1d6c4a23-42e9-4c1b-ad49-f5b5b2d9a905)

Expected behaviour:
Clicking delete on the third transformation always deletes that transformation.

**Comment by NathanOXIL** [comment]
Fixed
