### ISSUE TITLE
Query Cache shows all queries on the account rather than just the current query

### ISSUE THREAD

**Issue by peteroxil** [OxfordInfoLabs/kinintel#43]
![image](https://github.com/user-attachments/assets/304c99e2-1ab4-4fd9-a3ef-3875a3654190)
The query cache part of the query editor always shows all Query Caches on the account/project, rather than just the current query (like snapshots does).

Expected Behaviour:
Only the current query's caches should be shown.

**Comment by NathanOXIL** [comment]
This has been resolved. To make them query caches appear in the specific dataset you will need to re-save them from the master list - as there were additional fields required to be set to make the connection between cache and dataset.
